In [ ]:
import pandas as pd

In [3]:
ens_mems = [f"ens{i:03}" for i in range(1,127)]
df = pd.DataFrame({
    'ESM': ['CESM2']*126,
    'Inst': ['NCAR']*126,
    'run': ens_mems
})
df

       ESM  Inst     run
0    CESM2  NCAR  ens001
1    CESM2  NCAR  ens002
2    CESM2  NCAR  ens003
3    CESM2  NCAR  ens004
4    CESM2  NCAR  ens005
..     ...   ...     ...
121  CESM2  NCAR  ens122
122  CESM2  NCAR  ens123
123  CESM2  NCAR  ens124
124  CESM2  NCAR  ens125
125  CESM2  NCAR  ens126

[126 rows x 3 columns]

In [4]:
# Read the dataframe from the csv file
df = pd.read_csv("/home/onennecke/CMIP_models/CESM2_LE_runs.csv", dtype=str)
df.head()

     ESM Institution           run
0  CESM2        NCAR  LE2-1001_001
1  CESM2        NCAR  LE2-1011_001
2  CESM2        NCAR  LE2-1021_002
3  CESM2        NCAR  LE2-1031_002
4  CESM2        NCAR  LE2-1041_003

In [5]:
used_runs_CMIP = pd.read_csv('/home/onennecke/CMIP_models/CMIP6_runs_future.csv')

used_runs_CESM = pd.read_csv('/home/onennecke/CMIP_models/CESM2_LE_runs.csv')

used_runs = pd.concat([used_runs_CMIP, used_runs_CESM], ignore_index=True)

# Add one row with ERA5 using pd.concat
era5_row = pd.DataFrame([{
    'ESM': 'ERA5',
    'Institution': 'ECMWF',
    'run': 'hist'
}])
used_runs = pd.concat([used_runs, era5_row], ignore_index=True)
used_runs.head()

           ESM   Institution       run
0   ACCESS-CM2  CSIRO-ARCCSS  r4i1p1f1
1   ACCESS-CM2  CSIRO-ARCCSS  r5i1p1f1
2   ACCESS-CM2  CSIRO-ARCCSS  r1i1p1f1
3  BCC-CSM2-MR           BCC  r1i1p1f1
4        CESM2          NCAR  r4i1p1f1